employe_base/employe_base/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employe_base/main/urls.py
from django.urls import path

from .views import EmployeesList, EmployeeDetail, EmployeesListAlphabet

app_name = 'main'

urlpatterns = [
    path('', EmployeesList.as_view(), name='employeeslist'),
    path('alphabetic', EmployeesListAlphabet.as_view(), name='alphabetic'),
    path('employee/<pk>', EmployeeDetail.as_view(), name='employeedetail'),

]

employe_base/main/models.py
from django.db import models
from phone_field import PhoneField

class Department(models.Model):
    name = models.CharField(max_length=200, verbose_name='Отдел')

    class Meta:
        verbose_name = 'Отдел'
        verbose_name_plural = 'Отделы'
    
    def __str__(self):
        return str(self.name)

    def save(self, *args, **kwargs):
        """ Капитализируем """
        val = getattr(self, 'name', False)
        if val:
            setattr(self, 'name', val.capitalize())
        super(Department, self).save(*args, **kwargs)


class Employee(models.Model):
    first_name = models.CharField(max_length=200, verbose_name='Имя')
    last_name = models.CharField(max_length=200, verbose_name='Фамилия')
    middle_name = models.CharField(max_length=200, verbose_name='Отчество')
    birthday = models.DateField(verbose_name='Дата рождения')
    email = models.EmailField(max_length=100, verbose_name='E-mail')
    phone = PhoneField()
    start_date = models.DateField(verbose_name='Дата начала работы')
    end_date = models.DateField(verbose_name='Дата окончания работы', blank=True, null=True)
    position = models.CharField(max_length=200, verbose_name='Должность')
    department = models.ForeignKey(Department, on_delete=models.CASCADE, verbose_name='Отдел')

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'
    
    def __str__(self):
        return str(self.last_name)

    def save(self, *args, **kwargs):
        """ ФИО с большой капитализируем """

        for field_name in ['first_name', 'last_name', 'middle_name']:
            val = getattr(self, field_name, False)
            if val:
                setattr(self, field_name, val.capitalize())
        super(Employee, self).save(*args, **kwargs)

employe_base/main/views.py
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView

from .models import Employee, Department

class EmployeesList(ListView):
    """ Главная страница. Страница списка сотрудников с
        фильтрами по отделу и текущему статусу работы в компании """

    template_name = 'employeeslist.html'
    paginate_by = 10

    def get_context_data(self):
        """ Выводим в контекст паггинацию +
            Выводим в контекст все отделы для опций фильтра """

        context = super().get_context_data()
        queryset = Employee.objects.all()

        paginator = Paginator(queryset, self.paginate_by)
        page = self.request.GET.get('page')

        try:
            employees_page = paginator.page(page)
        except PageNotAnInteger:
            employees_page = paginator.page(1)
        except EmptyPage:
            employees_page = paginator.page(paginator.num_pages)

        departments = Department.objects.all().values_list('name', flat=True)

        context['departments'] = departments
        context['page'] = employees_page

        return context

    def get_queryset(self):
        """ Запрос данных, основанный на get запросе фильтра """

        queryset = Employee.objects.all()

        query_workers = self.request.GET.get('workers')
        query_department = self.request.GET.get('departments')

        if query_workers and query_department:
            if query_workers == 'current':
                queryset = Employee.objects.filter(
                    end_date__isnull=True,
                    department__name=query_department
                )
            elif query_workers == 'left':
                queryset = Employee.objects.filter(
                    end_date__isnull=False,
                    department__name=query_department
                )

        elif query_workers or query_department:
            if query_workers:
                if query_workers == 'current':
                    queryset = Employee.objects.filter(
                        end_date__isnull=True
                    )
                elif query_workers == 'left':
                    queryset = Employee.objects.filter(
                        end_date__isnull=False
                    )
            elif query_department:
                queryset = Employee.objects.filter(
                    department__name=query_department
                )

        return queryset


class EmployeeDetail(DetailView):
    """ Страница деталей по каждому сотруднику """

    queryset = Employee.objects.all()
    template_name = 'employeedetail.html'

    def get_object(self):
        obj = super(EmployeeDetail, self).get_object()
        return obj

class EmployeesListAlphabet(ListView):
    """ Страница списка сотрудников с фильтром по алфавитному указателю """

    template_name = 'alpabetic.html'

    def get_queryset(self):
        queryset = Employee.objects.all().order_by('last_name')

        query = self.request.GET.get('letters')

        if query:
            if query == 'А-Е':
                queryset = Employee.objects.filter(
                    Q(last_name__startswith='А') |
                    Q(last_name__startswith='Б') |
                    Q(last_name__startswith='В') |
                    Q(last_name__startswith='Г') |
                    Q(last_name__startswith='Д') |
                    Q(last_name__startswith='Е') |
                    Q(last_name__startswith='Ё')
                    ).order_by('last_name')

            elif query == 'Ж-М':
                queryset = Employee.objects.filter(
                    Q(last_name__startswith='Ж') |
                    Q(last_name__startswith='З') |
                    Q(last_name__startswith='И') |
                    Q(last_name__startswith='Й') |
                    Q(last_name__startswith='К') |
                    Q(last_name__startswith='Л') |
                    Q(last_name__startswith='М')
                    ).order_by('last_name')

            elif query == 'Н-Т':
                queryset = Employee.objects.filter(
                    Q(last_name__startswith='Н') |
                    Q(last_name__startswith='О') |
                    Q(last_name__startswith='П') |
                    Q(last_name__startswith='Р') |
                    Q(last_name__startswith='С') |
                    Q(last_name__startswith='Т')
                    ).order_by('last_name')

            elif query == 'У-Ш':
                queryset = Employee.objects.filter(
                    Q(last_name__startswith='У') |
                    Q(last_name__startswith='Ф') |
                    Q(last_name__startswith='Х') |
                    Q(last_name__startswith='Ц') |
                    Q(last_name__startswith='Ч') |
                    Q(last_name__startswith='Ш')
                    ).order_by('last_name')

            elif query == 'Щ-Я':
                queryset = Employee.objects.filter(
                    Q(last_name__startswith='Щ') |
                    Q(last_name__startswith='Ы') |
                    Q(last_name__startswith='Э') |
                    Q(last_name__startswith='Ю') |
                    Q(last_name__startswith='Я')
                    ).order_by('last_name')

        return queryset

employe_base/templates/alpabetic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Employee App</title>
</head>

<body>
    <div class="container-fluid">
            <div class="row">
                <div class="col">
                    <a href="{% url 'main:employeeslist' %}">На главную</a>
                </div>
                <div class="col">
                    <h3>Список сотрудников</h3>
                </div>
                <div class="col"></div>
            </div>
            <div class="row">
                <div class="col"></div>
                <div class="col">
                    <div class="row">
                        <a href="?letters=all" class='alphabetic-button'>
                            <button class="btn btn-success">Все</button>
                        </a>

                        <a href="?letters=А-Е" class='alphabetic-button'>
                            <button class="btn btn-success">А-Е</button>
                        </a>

                        <a href="?letters=Ж-М" class='alphabetic-button'>
                            <button class="btn btn-success">Ж-М</button>
                        </a>

                        <a href="?letters=Н-Т" class='alphabetic-button'>
                            <button class="btn btn-success">Н-Т</button>
                        </a>

                        <a href="?letters=У-Ш" class='alphabetic-button'>
                            <button class="btn btn-success">У-Ш</button>
                        </a>

                        <a href="?letters=Щ-Я" class='alphabetic-button'>
                            <button class="btn btn-success">Щ-Я</button>
                        </a>
                    </div>
                </div>
                <div class="col"></div>
            </div>
            <div class="row">
                <div class="col-sm"><b>Фамилия</b></div>
                <div class="col-sm"><b>Имя</b></div>
                <div class="col-sm"><b>Отчество</b></div>
            </div>
            {% for employee in object_list %}
            <div class="row">
                <div class="col-sm employee_item"><a href="{% url 'main:employeedetail' pk=employee.pk %}">{{ employee.last_name }}</a></div>
                <div class="col-sm employee_item">{{ employee.first_name }}</div>
                <div class="col-sm employee_item">{{ employee.middle_name }}</div>
            </div>
            {% endfor %}
    </div>
</body>

employe_base/templates/employeedetail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Сотрудник - {{ object.last_name }}</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col"></div>
            <div class="col-">
                <h3>Сотрудник - {{ object.last_name }} {{ object.first_name }} {{ object.middle_name }}</h3>
            </div>
            <div class="col">
                <a href="{% url 'main:employeeslist' %}">
                    <button class="btn btn-success">На главную</button>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col"></div>
            <div class="col-">
                <div class="row detail-item"><b>Дата рождения: </b> {{ object.birthday }}</div>
                <div class="row detail-item"><b>Электронная почта: </b> {{ object.email }}</div>
                <div class="row detail-item"><b>Телефон: </b> {{ object.phone }}</div>
                <div class="row detail-item"><b>Дата начала работы: </b> {{ object.start_date }}</div>
                {% if object.end_date %}
                <div class="row detail-item"><b>Дата окончания работы: </b> {{ object.end_date }}</div>
                {% else %}
                <div class="row detail-item"><b>Дата окончания работы: </b> - </div>
                {% endif %}
                <div class="row detail-item"><b>Должность: </b> {{ object.position }}</div>
                <div class="row detail-item"><b>Отдел: </b> {{ object.department }}</div>
            </div>
            <div class="col"></div>
        </div>
    </div>
</body>

employe_base/templates/employeeslist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>Employee App</title>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <a href="{% url 'main:alphabetic' %}">Найти по алфавитному указателю</a>
            </div>
            <div class="col">
                <h3>Список сотрудников</h3>
            </div>
            <div class="col">
                <form method="GET" id='filter' action="">
                    <select name="workers" form="filter">
                        <option value="">Все</option>
                        <option value="current">Только работающие</option>
                        <option value="left">Только не работающие</option>
                    </select>
                    <select name="departments" form="filter">
                        <option value="">Все</option>
                        {% for department in departments %}
                        <option value="{{ department }}">{{ department }}</option>
                        {% endfor %}
                    </select>
                    <button type="submit">Показать</button>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-sm"><b>Фамилия</b></div>
            <div class="col-sm"><b>Имя</b></div>
            <div class="col-sm"><b>Отчество</b></div>
        </div>
        {% for employee in object_list %}
        <div class="row">
            <div class="col-sm employee_item"><a href="{% url 'main:employeedetail' pk=employee.pk %}">{{ employee.last_name }}</a></div>
            <div class="col-sm employee_item">{{ employee.first_name }}</div>
            <div class="col-sm employee_item">{{ employee.middle_name }}</div>
        </div>
        {% endfor %}
        <div class="row">
            <div class="col"></div>
            <div class="col">
            {% if is_paginated %}
                <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li>
                        <span><a href="?page={{ page_obj.previous_page_number }}">Предыдущая </a></span>
                    </li>
                {% endif %}
                    <li>
                        <span>Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.</span>
                    </li>
                {% if page_obj.has_next %}
                    <li>
                        <span><a href="?page={{ page_obj.next_page_number }}"> Следующая</a></span>
                    </li>
                {% endif %}
                </ul>
                {% else %}
                    <p>Страница 1 из 1</p>
                {% endif %}
            </div>
            <div class="col"></div>
        </div>
    </div>
</body>
</html>

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>